name: PR Packager

on:
  workflow_dispatch:
  pull_request:

env:
  PYTHON_VERSION: "3.12"
  PACKAGE_NAME: Flow.Launcher.Plugin.YoudaoTranslate.zip

jobs:
  build:
    name: Build package
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install --upgrade pdm

      - name: Install project
        run: pdm install -dG dev

      - name: Lint
        run: pdm run ruff check .

      - name: Type check
        run: pdm run ty check .

      - name: Build executable plugin
        run: pdm run python build.py -t production

      - name: Pack zip
        shell: pwsh
        run: Compress-Archive -Path 'dist/run/*' -DestinationPath '${{ env.PACKAGE_NAME }}' -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.PACKAGE_NAME }}
